"""empty message

Revision ID: 062056abab41
Revises: 3ad5422060a7
Create Date: 2016-05-19 09:30:25.364143

"""

# revision identifiers, used by Alembic.
revision = '062056abab41'
down_revision = '3ad5422060a7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('formatted_title', sa.Unicode(length=64), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('formatted_title')

    ### end Alembic commands ###
