"""empty message

Revision ID: 205401b3a3a0
Revises: 38af18a59c80
Create Date: 2016-04-21 12:46:42.318348

"""

# revision identifiers, used by Alembic.
revision = '205401b3a3a0'
down_revision = '38af18a59c80'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('articles', sa.Column('viewcount', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'viewcount')
    op.drop_column('articles', 'timestamp')
    ### end Alembic commands ###
