"""empty message

Revision ID: 38af18a59c80
Revises: 02d164043dd2
Create Date: 2016-04-12 23:10:14.391075

"""

# revision identifiers, used by Alembic.
revision = '38af18a59c80'
down_revision = '02d164043dd2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('image_url', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'image_url')
    ### end Alembic commands ###
