"""empty message

Revision ID: 58e5d49cb165
Revises: 3ad5422060a7
Create Date: 2016-09-29 16:30:00.580191

"""

# revision identifiers, used by Alembic.
revision = '58e5d49cb165'
down_revision = '3ad5422060a7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        # batch_op.drop_column('disabled')
        batch_op.drop_constraint(None, 'email', type_='unique')
        batch_op.drop_constraint(None, 'md5', type_='unique')
        batch_op.drop_constraint(None, 'content', type_='unique')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    # with op.batch_alter_table('comments', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('disabled', sa.BOOLEAN(), nullable=True))

    ### end Alembic commands ###
