"""empty message

Revision ID: 5fce93ec0c29
Revises: 148d1dcc5fec
Create Date: 2016-09-29 09:06:47.042013

"""

# revision identifiers, used by Alembic.
revision = '5fce93ec0c29'
down_revision = '148d1dcc5fec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #with op.batch_alter_table('articles', schema=None) as batch_op:
     #   batch_op.create_unique_constraint(None, ['title'])
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    ### end Alembic commands ###
