"""empty message

Revision ID: 65f77abda0ce
Revises: 75819dd906f8
Create Date: 2016-05-18 17:17:59.452504

"""

# revision identifiers, used by Alembic.
revision = '65f77abda0ce'
down_revision = '75819dd906f8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disabled', sa.Boolean(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('disabled')

    ### end Alembic commands ###
