"""empty message

Revision ID: 75819dd906f8
Revises: f71daff0a3d0
Create Date: 2016-05-17 20:02:00.315873

"""

# revision identifiers, used by Alembic.
revision = '75819dd906f8'
down_revision = 'f71daff0a3d0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    ### end Alembic commands ###
