"""empty message

Revision ID: d0ff2f23d725
Revises: 65f77abda0ce
Create Date: 2016-05-18 20:38:45.930949

"""

# revision identifiers, used by Alembic.
revision = 'd0ff2f23d725'
down_revision = '65f77abda0ce'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('homepage', sa.String(length=64), nullable=True))
        #batch_op.create_unique_constraint(None, ['homepage'])

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('homepage')

    ### end Alembic commands ###
