"""empty message

Revision ID: f71daff0a3d0
Revises: 44e23f9db77f
Create Date: 2016-04-24 21:53:35.533167

"""

# revision identifiers, used by Alembic.
revision = 'f71daff0a3d0'
down_revision = '44e23f9db77f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
#    op.add_column('articles', sa.Column('formatted_title', sa.Unicode(length=64), nullable=True))
#    op.create_unique_constraint(None, 'articles', ['formatted_title'])
#    op.drop_column('articles', 'viewcount')
    ### end Alembic commands ###
    with op.batch_alter_table('articles') as batch_op:
            batch_op.drop_column('viewcount')


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('viewcount', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'articles', type_='unique')
    op.drop_column('articles', 'formatted_title')
    ### end Alembic commands ###
